DELETE FROM ITEMS;
DELETE FROM CATEGORIES;
DELETE FROM STORES;
ALTER TABLE ITEMS ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE CATEGORIES ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE STORES ALTER COLUMN ID GENERATED BY DEFAULT AS IDENTITY (START WITH 1);

-- Stores
insert into STORES (NAME, DESCRIPTION, LOGO) values ('Italian specialities', 'Pizza and pasta lovers', (SELECT  BulkColumn FROM OPENROWSET(BULK  N'C:\Users\david\IdeaProjects\sap\db-installer-sap\sql\images\store-pizza-logo.png', SINGLE_BLOB) AS x))
insert into STORES (NAME, DESCRIPTION, LOGO) values ('San Barbaque', 'Best bbq in town', (SELECT  BulkColumn FROM OPENROWSET(BULK  N'C:\Users\david\IdeaProjects\sap\db-installer-sap\sql\images\store-restaurant-logo.png', SINGLE_BLOB) AS x))
-- Categories
insert into CATEGORIES (STORE_ID, NAME, DESCRIPTION, IMAGE) values (1, 'Pizza', 'Homemade tasty pizza', (SELECT  BulkColumn FROM OPENROWSET(BULK  N'C:\Users\david\IdeaProjects\sap\db-installer-sap\sql\images\category-pizza.png', SINGLE_BLOB) AS x))
insert into CATEGORIES (STORE_ID, NAME, DESCRIPTION, IMAGE) values (2, 'Burguer', 'Try our great burguer selection', (SELECT  BulkColumn FROM OPENROWSET(BULK  N'C:\Users\david\IdeaProjects\sap\db-installer-sap\sql\images\category-burguer.png', SINGLE_BLOB) AS x))
insert into CATEGORIES (STORE_ID, NAME, DESCRIPTION, IMAGE) values (1, 'Beverages', 'Hot or cold, whatever you prefer', (SELECT  BulkColumn FROM OPENROWSET(BULK  N'C:\Users\david\IdeaProjects\sap\db-installer-sap\sql\images\category-beer.png', SINGLE_BLOB) AS x))
insert into CATEGORIES (STORE_ID, NAME, DESCRIPTION, IMAGE) values (2, 'Meat', '', (SELECT  BulkColumn FROM OPENROWSET(BULK  N'C:\Users\david\IdeaProjects\sap\db-installer-sap\sql\images\category-steak.png', SINGLE_BLOB) AS x))
insert into CATEGORIES (STORE_ID, NAME, DESCRIPTION, IMAGE) values (2, 'Seafood', '', (SELECT  BulkColumn FROM OPENROWSET(BULK  N'C:\Users\david\IdeaProjects\sap\db-installer-sap\sql\images\category-fish.png', SINGLE_BLOB) AS x))
insert into CATEGORIES (STORE_ID, NAME, DESCRIPTION, IMAGE) values (2, 'Salad', 'Fresh salads', (SELECT  BulkColumn FROM OPENROWSET(BULK  N'C:\Users\david\IdeaProjects\sap\db-installer-sap\sql\images\category-salad.png', SINGLE_BLOB) AS x))
insert into CATEGORIES (STORE_ID, NAME, DESCRIPTION, IMAGE) values (2, 'Hot beverages', '', (SELECT  BulkColumn FROM OPENROWSET(BULK  N'C:\Users\david\IdeaProjects\sap\db-installer-sap\sql\images\category-tea.png', SINGLE_BLOB) AS x))
insert into CATEGORIES (STORE_ID, NAME, DESCRIPTION, IMAGE) values (2, 'Cold beverages', '', (SELECT  BulkColumn FROM OPENROWSET(BULK  N'C:\Users\david\IdeaProjects\sap\db-installer-sap\sql\images\category-beer-2.png', SINGLE_BLOB) AS x))
-- Items

insert into ITEMS (category_id, name, description, price, currency) values (1, 'Pizza quattro stagioni', 'mmmm', '14.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (1, 'Pizza capricciosa', 'mmmm', '17.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (1, 'Pizza margherita', 'mmmm', '14.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (1, 'Pizza calzone', 'mmmm', '17.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (2, 'Classic Cheeseburger', '', '8', '€')
insert into ITEMS (category_id, name, description, price, currency) values (2, 'Garlic Lovers Burger', '', '12.75', '€')
insert into ITEMS (category_id, name, description, price, currency) values (2, 'Turkey Burger', '', '13.75', '€')
insert into ITEMS (category_id, name, description, price, currency) values (2, 'Black Bean Burger', '', '14.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (3, 'Water', '', '2,00', '€')
insert into ITEMS (category_id, name, description, price, currency) values (3, 'Wine', '', '3.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (3, 'Beer', '', '3.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (4, 'Steak', '', '18.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (4, 'Bistec encebollado', '', '20.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (4, 'Cincinnati chili', '', '16.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (4, 'Smocked duck', '', '21.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (5, 'Brown Stew Fish', '', '18.75', '€')
insert into ITEMS (category_id, name, description, price, currency) values (5, 'New Orleans-Style BBQ Shrimp', '', '22.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (5, 'Steamed fish', '', '19.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (6, 'Greek salad', '', '11.75', '€')
insert into ITEMS (category_id, name, description, price, currency) values (6, 'Caprese', '', '12.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (6, 'Tabbouleh', '', '13.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (7, 'Coffee', '', '1.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (7, 'Tea', '', '1.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (8, 'Water', '', '1.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (8, 'Beer', '', '2.50', '€')
insert into ITEMS (category_id, name, description, price, currency) values (8, 'Wine', '', '2.50', '€')